// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4yBVxiO9QN9YfrMDmMpOHc3NwMsaGL00',
    appId: '1:815170206585:web:ecd2e1563c5366fd8b8da8',
    messagingSenderId: '815170206585',
    projectId: 'appdelivery-70a7b',
    authDomain: 'appdelivery-70a7b.firebaseapp.com',
    storageBucket: 'appdelivery-70a7b.appspot.com',
    measurementId: 'G-6E007JMPPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX6SyUC0f51KoWRDMHGn3rzRpoGAyOu04',
    appId: '1:815170206585:android:b6a92cc4e70fb3868b8da8',
    messagingSenderId: '815170206585',
    projectId: 'appdelivery-70a7b',
    storageBucket: 'appdelivery-70a7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZFfyzJ5pnnckILN0E4j7qbjstClqNRF4',
    appId: '1:815170206585:ios:9fe292d4295699fb8b8da8',
    messagingSenderId: '815170206585',
    projectId: 'appdelivery-70a7b',
    storageBucket: 'appdelivery-70a7b.appspot.com',
    iosClientId: '815170206585-5ds8mbhfllibr16qeckltqvfm1ch298b.apps.googleusercontent.com',
    iosBundleId: 'com.app.appdelivery',
  );
}
